//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_Project_A_2022___Clinic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCI_Project_A_2022___Clinic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novo naručenje.
        /// </summary>
        public static string AppointmentsPageAddAppointmentBtn {
            get {
                return ResourceManager.GetString("AppointmentsPageAddAppointmentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum naručenja.
        /// </summary>
        public static string AppointmentsPageDateDP {
            get {
                return ResourceManager.GetString("AppointmentsPageDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vrijeme naručenja.
        /// </summary>
        public static string AppointmentsPageDateTimeDG {
            get {
                return ResourceManager.GetString("AppointmentsPageDateTimeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string AppointmentsPageDoctorCB {
            get {
                return ResourceManager.GetString("AppointmentsPageDoctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string AppointmentsPageDoctorDG {
            get {
                return ResourceManager.GetString("AppointmentsPageDoctorDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlog.
        /// </summary>
        public static string AppointmentsPageReasonDG {
            get {
                return ResourceManager.GetString("AppointmentsPageReasonDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite.
        /// </summary>
        public static string AppointmentsPageSearchBtn {
            get {
                return ResourceManager.GetString("AppointmentsPageSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga naručenja.
        /// </summary>
        public static string AppointmentsPageSearchLb {
            get {
                return ResourceManager.GetString("AppointmentsPageSearchLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o naručenju.
        /// </summary>
        public static string AppointmentWindowAppointmentData {
            get {
                return ResourceManager.GetString("AppointmentWindowAppointmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkažite.
        /// </summary>
        public static string AppointmentWindowCancelBtn {
            get {
                return ResourceManager.GetString("AppointmentWindowCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum naručenja.
        /// </summary>
        public static string AppointmentWindowDateDP {
            get {
                return ResourceManager.GetString("AppointmentWindowDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string AppointmentWindowDoctorCB {
            get {
                return ResourceManager.GetString("AppointmentWindowDoctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o ljekaru.
        /// </summary>
        public static string AppointmentWindowDoctorData {
            get {
                return ResourceManager.GetString("AppointmentWindowDoctorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string AppointmentWindowJmbTb {
            get {
                return ResourceManager.GetString("AppointmentWindowJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidentirajte novi pregled.
        /// </summary>
        public static string AppointmentWindowNewExamBtn {
            get {
                return ResourceManager.GetString("AppointmentWindowNewExamBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o pacijentu.
        /// </summary>
        public static string AppointmentWindowPatientData {
            get {
                return ResourceManager.GetString("AppointmentWindowPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlog.
        /// </summary>
        public static string AppointmentWindowReasonTb {
            get {
                return ResourceManager.GetString("AppointmentWindowReasonTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvajte.
        /// </summary>
        public static string AppointmentWindowSaveBtn {
            get {
                return ResourceManager.GetString("AppointmentWindowSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme naručenja.
        /// </summary>
        public static string AppointmentWindowTimeTP {
            get {
                return ResourceManager.GetString("AppointmentWindowTimeTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naručenje.
        /// </summary>
        public static string AppointmentWindowTitle {
            get {
                return ResourceManager.GetString("AppointmentWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clinic_reception1 {
            get {
                object obj = ResourceManager.GetObject("clinic_reception1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste unijeli korisničko ime ili lozinku..
        /// </summary>
        public static string CredentialsMissing {
            get {
                return ResourceManager.GetString("CredentialsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novog zaposlenog.
        /// </summary>
        public static string EmployeesPageAddEmployeeBtn {
            get {
                return ResourceManager.GetString("EmployeesPageAddEmployeeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail adresa.
        /// </summary>
        public static string EmployeesPageEmailDG {
            get {
                return ResourceManager.GetString("EmployeesPageEmailDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno zaposlen.
        /// </summary>
        public static string EmployeesPageEmployedDG {
            get {
                return ResourceManager.GetString("EmployeesPageEmployedDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string EmployeesPageFirstNameDG {
            get {
                return ResourceManager.GetString("EmployeesPageFirstNameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string EmployeesPageFirstNameTb {
            get {
                return ResourceManager.GetString("EmployeesPageFirstNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string EmployeesPageJmbDG {
            get {
                return ResourceManager.GetString("EmployeesPageJmbDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string EmployeesPageJmbTb {
            get {
                return ResourceManager.GetString("EmployeesPageJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string EmployeesPageLastNameDG {
            get {
                return ResourceManager.GetString("EmployeesPageLastNameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string EmployeesPageLastNameTb {
            get {
                return ResourceManager.GetString("EmployeesPageLastNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        public static string EmployeesPageRoleCB {
            get {
                return ResourceManager.GetString("EmployeesPageRoleCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        public static string EmployeesPageRoleDG {
            get {
                return ResourceManager.GetString("EmployeesPageRoleDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite.
        /// </summary>
        public static string EmployeesPageSearchBtn {
            get {
                return ResourceManager.GetString("EmployeesPageSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga zaposlenih.
        /// </summary>
        public static string EmployeesPageSearchLb {
            get {
                return ResourceManager.GetString("EmployeesPageSearchLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string EmployeesPageUsernameDG {
            get {
                return ResourceManager.GetString("EmployeesPageUsernameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa stanovanja.
        /// </summary>
        public static string EmployeeWindowAddressTb {
            get {
                return ResourceManager.GetString("EmployeeWindowAddressTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne informacije.
        /// </summary>
        public static string EmployeeWindowBasicInfo {
            get {
                return ResourceManager.GetString("EmployeeWindowBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkažite.
        /// </summary>
        public static string EmployeeWindowCancelBtn {
            get {
                return ResourceManager.GetString("EmployeeWindowCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto rođenja.
        /// </summary>
        public static string EmployeeWindowCityTb {
            get {
                return ResourceManager.GetString("EmployeeWindowCityTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt informacije.
        /// </summary>
        public static string EmployeeWindowContactInfo {
            get {
                return ResourceManager.GetString("EmployeeWindowContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredencijali.
        /// </summary>
        public static string EmployeeWindowCredentials {
            get {
                return ResourceManager.GetString("EmployeeWindowCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string EmployeeWindowDateDP {
            get {
                return ResourceManager.GetString("EmployeeWindowDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljne informacije.
        /// </summary>
        public static string EmployeeWindowDetailedInfo {
            get {
                return ResourceManager.GetString("EmployeeWindowDetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmployeeWindowEmailTb {
            get {
                return ResourceManager.GetString("EmployeeWindowEmailTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno zaposlen.
        /// </summary>
        public static string EmployeeWindowEmployedCb {
            get {
                return ResourceManager.GetString("EmployeeWindowEmployedCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string EmployeeWindowFirstNameTb {
            get {
                return ResourceManager.GetString("EmployeeWindowFirstNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zaposlenja.
        /// </summary>
        public static string EmployeeWindowHireDateDP {
            get {
                return ResourceManager.GetString("EmployeeWindowHireDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string EmployeeWindowJmbTb {
            get {
                return ResourceManager.GetString("EmployeeWindowJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string EmployeeWindowLastNameTb {
            get {
                return ResourceManager.GetString("EmployeeWindowLastNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string EmployeeWindowPassword {
            get {
                return ResourceManager.GetString("EmployeeWindowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stručna sprema.
        /// </summary>
        public static string EmployeeWindowQualificationTb {
            get {
                return ResourceManager.GetString("EmployeeWindowQualificationTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        public static string EmployeeWindowRoleCB {
            get {
                return ResourceManager.GetString("EmployeeWindowRoleCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plata.
        /// </summary>
        public static string EmployeeWindowSalaryTb {
            get {
                return ResourceManager.GetString("EmployeeWindowSalaryTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvajte.
        /// </summary>
        public static string EmployeeWindowSaveBtn {
            get {
                return ResourceManager.GetString("EmployeeWindowSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled zaposlenog.
        /// </summary>
        public static string EmployeeWindowTitle {
            get {
                return ResourceManager.GetString("EmployeeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje.
        /// </summary>
        public static string EmployeeWindowTitleTb {
            get {
                return ResourceManager.GetString("EmployeeWindowTitleTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string EmployeeWindowUsernameTb {
            get {
                return ResourceManager.GetString("EmployeeWindowUsernameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novi pregled.
        /// </summary>
        public static string ExamsPageAddExamBtn {
            get {
                return ResourceManager.GetString("ExamsPageAddExamBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum pregleda.
        /// </summary>
        public static string ExamsPageDateDP {
            get {
                return ResourceManager.GetString("ExamsPageDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vrijeme pregleda.
        /// </summary>
        public static string ExamsPageDateTimeDG {
            get {
                return ResourceManager.GetString("ExamsPageDateTimeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra dijagnoze.
        /// </summary>
        public static string ExamsPageDiagnosisCodeDG {
            get {
                return ResourceManager.GetString("ExamsPageDiagnosisCodeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string ExamsPageDoctorCB {
            get {
                return ResourceManager.GetString("ExamsPageDoctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string ExamsPageDoctorDG {
            get {
                return ResourceManager.GetString("ExamsPageDoctorDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta pregleda.
        /// </summary>
        public static string ExamsPageExamTypeDG {
            get {
                return ResourceManager.GetString("ExamsPageExamTypeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite.
        /// </summary>
        public static string ExamsPageSearchBtn {
            get {
                return ResourceManager.GetString("ExamsPageSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga pregleda.
        /// </summary>
        public static string ExamsPageSearchLb {
            get {
                return ResourceManager.GetString("ExamsPageSearchLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkažite.
        /// </summary>
        public static string ExamWindowCancelBtn {
            get {
                return ResourceManager.GetString("ExamWindowCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra dijagnoze.
        /// </summary>
        public static string ExamWindowDiagnosisCodeTb {
            get {
                return ResourceManager.GetString("ExamWindowDiagnosisCodeTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string ExamWindowDoctorCB {
            get {
                return ResourceManager.GetString("ExamWindowDoctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o ljekaru.
        /// </summary>
        public static string ExamWindowDoctorData {
            get {
                return ResourceManager.GetString("ExamWindowDoctorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o pregledu.
        /// </summary>
        public static string ExamWindowExamData {
            get {
                return ResourceManager.GetString("ExamWindowExamData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta pregleda.
        /// </summary>
        public static string ExamWindowExamTypeCB {
            get {
                return ResourceManager.GetString("ExamWindowExamTypeCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv ustanove.
        /// </summary>
        public static string ExamWindowInstituionNameTb {
            get {
                return ResourceManager.GetString("ExamWindowInstituionNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra ustanove.
        /// </summary>
        public static string ExamWindowInstitutionCodeTb {
            get {
                return ResourceManager.GetString("ExamWindowInstitutionCodeTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način upotrebe.
        /// </summary>
        public static string ExamWindowInstructionTb {
            get {
                return ResourceManager.GetString("ExamWindowInstructionTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string ExamWindowJmbTb {
            get {
                return ResourceManager.GetString("ExamWindowJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijek.
        /// </summary>
        public static string ExamWindowMedicationCB {
            get {
                return ResourceManager.GetString("ExamWindowMedicationCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o pacijentu.
        /// </summary>
        public static string ExamWindowPatientData {
            get {
                return ResourceManager.GetString("ExamWindowPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recept.
        /// </summary>
        public static string ExamWindowPrescriptionCb {
            get {
                return ResourceManager.GetString("ExamWindowPrescriptionCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o receptu.
        /// </summary>
        public static string ExamWindowPrescriptionData {
            get {
                return ResourceManager.GetString("ExamWindowPrescriptionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uputnica.
        /// </summary>
        public static string ExamWindowRefferalCb {
            get {
                return ResourceManager.GetString("ExamWindowRefferalCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o uputnici.
        /// </summary>
        public static string ExamWindowRefferalData {
            get {
                return ResourceManager.GetString("ExamWindowRefferalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta uputnice.
        /// </summary>
        public static string ExamWindowRefferalTypeTb {
            get {
                return ResourceManager.GetString("ExamWindowRefferalTypeTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalaz i mišljenje.
        /// </summary>
        public static string ExamWindowReportTb {
            get {
                return ResourceManager.GetString("ExamWindowReportTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvajte.
        /// </summary>
        public static string ExamWindowSaveBtn {
            get {
                return ResourceManager.GetString("ExamWindowSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        public static string ExamWindowTitle {
            get {
                return ResourceManager.GetString("ExamWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešni pristupni podaci..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string LoginWindowBtn {
            get {
                return ResourceManager.GetString("LoginWindowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string LoginWindowPasswordLb {
            get {
                return ResourceManager.GetString("LoginWindowPasswordLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinika.
        /// </summary>
        public static string LoginWindowTitleLb {
            get {
                return ResourceManager.GetString("LoginWindowTitleLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string LoginWindowUsernameLb {
            get {
                return ResourceManager.GetString("LoginWindowUsernameLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracija.
        /// </summary>
        public static string MainWindowAdministrationBtn {
            get {
                return ResourceManager.GetString("MainWindowAdministrationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naručenja.
        /// </summary>
        public static string MainWindowAppointmentsBtn {
            get {
                return ResourceManager.GetString("MainWindowAppointmentsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifarnici.
        /// </summary>
        public static string MainWindowCodebooksBtn {
            get {
                return ResourceManager.GetString("MainWindowCodebooksBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string MainWindowExamsBtn {
            get {
                return ResourceManager.GetString("MainWindowExamsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string MainWindowLogoutBtn {
            get {
                return ResourceManager.GetString("MainWindowLogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijenti.
        /// </summary>
        public static string MainWindowPatientsBtn {
            get {
                return ResourceManager.GetString("MainWindowPatientsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string MainWindowSettingsBtn {
            get {
                return ResourceManager.GetString("MainWindowSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinika HCI.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novog pacijenta.
        /// </summary>
        public static string PatientsPageAddPatientBtn {
            get {
                return ResourceManager.GetString("PatientsPageAddPatientBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string PatientsPageAddressDG {
            get {
                return ResourceManager.GetString("PatientsPageAddressDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string PatientsPageCityDG {
            get {
                return ResourceManager.GetString("PatientsPageCityDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail adresa.
        /// </summary>
        public static string PatientsPageEmailDG {
            get {
                return ResourceManager.GetString("PatientsPageEmailDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string PatientsPageFirstNameDG {
            get {
                return ResourceManager.GetString("PatientsPageFirstNameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string PatientsPageFirstNameTb {
            get {
                return ResourceManager.GetString("PatientsPageFirstNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string PatientsPageJmbDG {
            get {
                return ResourceManager.GetString("PatientsPageJmbDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string PatientsPageJmbTb {
            get {
                return ResourceManager.GetString("PatientsPageJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string PatientsPageLastNameDG {
            get {
                return ResourceManager.GetString("PatientsPageLastNameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string PatientsPageLastNameTb {
            get {
                return ResourceManager.GetString("PatientsPageLastNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string PatientsPagePhoneDG {
            get {
                return ResourceManager.GetString("PatientsPagePhoneDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite.
        /// </summary>
        public static string PatientsPageSearchBtn {
            get {
                return ResourceManager.GetString("PatientsPageSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga pacijenata.
        /// </summary>
        public static string PatientsPageSearchLb {
            get {
                return ResourceManager.GetString("PatientsPageSearchLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa stanovanja.
        /// </summary>
        public static string PatientWindowAddressTb {
            get {
                return ResourceManager.GetString("PatientWindowAddressTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne informacije.
        /// </summary>
        public static string PatientWindowBasicInfo {
            get {
                return ResourceManager.GetString("PatientWindowBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krvna grupa.
        /// </summary>
        public static string PatientWindowBloodTypeTb {
            get {
                return ResourceManager.GetString("PatientWindowBloodTypeTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkažite.
        /// </summary>
        public static string PatientWindowCancelBtn {
            get {
                return ResourceManager.GetString("PatientWindowCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zdravstvenog kartona.
        /// </summary>
        public static string PatientWindowCardNumberTb {
            get {
                return ResourceManager.GetString("PatientWindowCardNumberTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto rođenja.
        /// </summary>
        public static string PatientWindowCityTb {
            get {
                return ResourceManager.GetString("PatientWindowCityTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra dijagnoze.
        /// </summary>
        public static string PatientWindowCodeDG {
            get {
                return ResourceManager.GetString("PatientWindowCodeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt informacije.
        /// </summary>
        public static string PatientWindowContactInfo {
            get {
                return ResourceManager.GetString("PatientWindowContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vrijeme pregleda.
        /// </summary>
        public static string PatientWindowDateDG {
            get {
                return ResourceManager.GetString("PatientWindowDateDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string PatientWindowDateDP {
            get {
                return ResourceManager.GetString("PatientWindowDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vrijeme naručenja.
        /// </summary>
        public static string PatientWindowDateTab3DG {
            get {
                return ResourceManager.GetString("PatientWindowDateTab3DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum preboljenja.
        /// </summary>
        public static string PatientWindowDateTab4DG {
            get {
                return ResourceManager.GetString("PatientWindowDateTab4DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljne informacije.
        /// </summary>
        public static string PatientWindowDetailedInfo {
            get {
                return ResourceManager.GetString("PatientWindowDetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string PatientWindowDoctorDG {
            get {
                return ResourceManager.GetString("PatientWindowDoctorDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string PatientWindowDoctorTab3DG {
            get {
                return ResourceManager.GetString("PatientWindowDoctorTab3DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string PatientWindowDoctorTab4DG {
            get {
                return ResourceManager.GetString("PatientWindowDoctorTab4DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string PatientWindowEmailTb {
            get {
                return ResourceManager.GetString("PatientWindowEmailTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta pregleda.
        /// </summary>
        public static string PatientWindowExamTypeDG {
            get {
                return ResourceManager.GetString("PatientWindowExamTypeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string PatientWindowFirstNameTb {
            get {
                return ResourceManager.GetString("PatientWindowFirstNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv bolesti.
        /// </summary>
        public static string PatientWindowIllnessTab4DG {
            get {
                return ResourceManager.GetString("PatientWindowIllnessTab4DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string PatientWindowJmbTb {
            get {
                return ResourceManager.GetString("PatientWindowJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string PatientWindowLastNameTb {
            get {
                return ResourceManager.GetString("PatientWindowLastNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bračni status.
        /// </summary>
        public static string PatientWindowMarriageTb {
            get {
                return ResourceManager.GetString("PatientWindowMarriageTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novo naručenje.
        /// </summary>
        public static string PatientWindowNewAppointmentBtn {
            get {
                return ResourceManager.GetString("PatientWindowNewAppointmentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novi pregled.
        /// </summary>
        public static string PatientWindowNewExamBtn {
            get {
                return ResourceManager.GetString("PatientWindowNewExamBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novo preboljenje.
        /// </summary>
        public static string PatientWindowNewRecoveryBtn {
            get {
                return ResourceManager.GetString("PatientWindowNewRecoveryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt telefon.
        /// </summary>
        public static string PatientWindowPhoneTb {
            get {
                return ResourceManager.GetString("PatientWindowPhoneTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlog.
        /// </summary>
        public static string PatientWindowReasonTab3DG {
            get {
                return ResourceManager.GetString("PatientWindowReasonTab3DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvajte.
        /// </summary>
        public static string PatientWindowSavebtn {
            get {
                return ResourceManager.GetString("PatientWindowSavebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o pacijentu.
        /// </summary>
        public static string PatientWindowTab1 {
            get {
                return ResourceManager.GetString("PatientWindowTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi pacijenta.
        /// </summary>
        public static string PatientWindowTab2 {
            get {
                return ResourceManager.GetString("PatientWindowTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naručenja pacijenta.
        /// </summary>
        public static string PatientWindowTab3 {
            get {
                return ResourceManager.GetString("PatientWindowTab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preboljenja pacijenta.
        /// </summary>
        public static string PatientWindowTab4 {
            get {
                return ResourceManager.GetString("PatientWindowTab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled pacijenta.
        /// </summary>
        public static string PatientWindowTitle {
            get {
                return ResourceManager.GetString("PatientWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkažite.
        /// </summary>
        public static string RecoveryWindowCancelBtn {
            get {
                return ResourceManager.GetString("RecoveryWindowCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum preboljenja.
        /// </summary>
        public static string RecoveryWindowDateDP {
            get {
                return ResourceManager.GetString("RecoveryWindowDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string RecoveryWindowDoctorCB {
            get {
                return ResourceManager.GetString("RecoveryWindowDoctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o ljekaru.
        /// </summary>
        public static string RecoveryWindowDoctorData {
            get {
                return ResourceManager.GetString("RecoveryWindowDoctorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolest.
        /// </summary>
        public static string RecoveryWindowIllnessCB {
            get {
                return ResourceManager.GetString("RecoveryWindowIllnessCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string RecoveryWindowJmbTb {
            get {
                return ResourceManager.GetString("RecoveryWindowJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o pacijentu.
        /// </summary>
        public static string RecoveryWindowPatientData {
            get {
                return ResourceManager.GetString("RecoveryWindowPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o preboljenju.
        /// </summary>
        public static string RecoveryWindowRecoveryData {
            get {
                return ResourceManager.GetString("RecoveryWindowRecoveryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvajte.
        /// </summary>
        public static string RecoveryWindowSaveBtn {
            get {
                return ResourceManager.GetString("RecoveryWindowSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preboljenje.
        /// </summary>
        public static string RecoveryWindowTitle {
            get {
                return ResourceManager.GetString("RecoveryWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavite.
        /// </summary>
        public static string RoleWindowContinueBtn {
            get {
                return ResourceManager.GetString("RoleWindowContinueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        public static string RoleWindowRoleCb {
            get {
                return ResourceManager.GetString("RoleWindowRoleCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbor uloge.
        /// </summary>
        public static string RoleWindowTitle {
            get {
                return ResourceManager.GetString("RoleWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite ulogu zaposlenog.
        /// </summary>
        public static string RoleWindowTitleLb {
            get {
                return ResourceManager.GetString("RoleWindowTitleLb", resourceCulture);
            }
        }
    }
}
