//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_Project_A_2022___Clinic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCI_Project_A_2022___Clinic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o naručenju.
        /// </summary>
        public static string AppointmentWindowAppointmentData {
            get {
                return ResourceManager.GetString("AppointmentWindowAppointmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkažite.
        /// </summary>
        public static string AppointmentWindowCancelBtn {
            get {
                return ResourceManager.GetString("AppointmentWindowCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum naručenja.
        /// </summary>
        public static string AppointmentWindowDateDP {
            get {
                return ResourceManager.GetString("AppointmentWindowDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string AppointmentWindowDoctorCB {
            get {
                return ResourceManager.GetString("AppointmentWindowDoctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o ljekaru.
        /// </summary>
        public static string AppointmentWindowDoctorData {
            get {
                return ResourceManager.GetString("AppointmentWindowDoctorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string AppointmentWindowJmbTb {
            get {
                return ResourceManager.GetString("AppointmentWindowJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o pacijentu.
        /// </summary>
        public static string AppointmentWindowPatientData {
            get {
                return ResourceManager.GetString("AppointmentWindowPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlog.
        /// </summary>
        public static string AppointmentWindowReasonTb {
            get {
                return ResourceManager.GetString("AppointmentWindowReasonTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvajte.
        /// </summary>
        public static string AppointmentWindowSaveBtn {
            get {
                return ResourceManager.GetString("AppointmentWindowSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme naručenja.
        /// </summary>
        public static string AppointmentWindowTimeTP {
            get {
                return ResourceManager.GetString("AppointmentWindowTimeTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naručenje.
        /// </summary>
        public static string AppointmentWindowTitle {
            get {
                return ResourceManager.GetString("AppointmentWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clinic_reception1 {
            get {
                object obj = ResourceManager.GetObject("clinic_reception1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste unijeli korisničko ime ili lozinku..
        /// </summary>
        public static string CredentialsMissing {
            get {
                return ResourceManager.GetString("CredentialsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešni pristupni podaci..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string LoginWindowBtn {
            get {
                return ResourceManager.GetString("LoginWindowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string LoginWindowPasswordLb {
            get {
                return ResourceManager.GetString("LoginWindowPasswordLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinika.
        /// </summary>
        public static string LoginWindowTitleLb {
            get {
                return ResourceManager.GetString("LoginWindowTitleLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string LoginWindowUsernameLb {
            get {
                return ResourceManager.GetString("LoginWindowUsernameLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracija.
        /// </summary>
        public static string MainWindowAdministrationBtn {
            get {
                return ResourceManager.GetString("MainWindowAdministrationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naručenja.
        /// </summary>
        public static string MainWindowAppointmentsBtn {
            get {
                return ResourceManager.GetString("MainWindowAppointmentsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifarnici.
        /// </summary>
        public static string MainWindowCodebooksBtn {
            get {
                return ResourceManager.GetString("MainWindowCodebooksBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string MainWindowExamsBtn {
            get {
                return ResourceManager.GetString("MainWindowExamsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string MainWindowLogoutBtn {
            get {
                return ResourceManager.GetString("MainWindowLogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijenti.
        /// </summary>
        public static string MainWindowPatientsBtn {
            get {
                return ResourceManager.GetString("MainWindowPatientsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string MainWindowSettingsBtn {
            get {
                return ResourceManager.GetString("MainWindowSettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinika HCI.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novog pacijenta.
        /// </summary>
        public static string PatientsPageAddPatientBtn {
            get {
                return ResourceManager.GetString("PatientsPageAddPatientBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string PatientsPageAddressDG {
            get {
                return ResourceManager.GetString("PatientsPageAddressDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string PatientsPageCityDG {
            get {
                return ResourceManager.GetString("PatientsPageCityDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail adresa.
        /// </summary>
        public static string PatientsPageEmailDG {
            get {
                return ResourceManager.GetString("PatientsPageEmailDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string PatientsPageFirstNameDG {
            get {
                return ResourceManager.GetString("PatientsPageFirstNameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string PatientsPageFirstNameTb {
            get {
                return ResourceManager.GetString("PatientsPageFirstNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string PatientsPageJmbDG {
            get {
                return ResourceManager.GetString("PatientsPageJmbDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string PatientsPageJmbTb {
            get {
                return ResourceManager.GetString("PatientsPageJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string PatientsPageLastNameDG {
            get {
                return ResourceManager.GetString("PatientsPageLastNameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string PatientsPageLastNameTb {
            get {
                return ResourceManager.GetString("PatientsPageLastNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string PatientsPagePhoneDG {
            get {
                return ResourceManager.GetString("PatientsPagePhoneDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite.
        /// </summary>
        public static string PatientsPageSearchBtn {
            get {
                return ResourceManager.GetString("PatientsPageSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga pacijenata.
        /// </summary>
        public static string PatientsPageSearchLb {
            get {
                return ResourceManager.GetString("PatientsPageSearchLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa stanovanja.
        /// </summary>
        public static string PatientWindowAddressTb {
            get {
                return ResourceManager.GetString("PatientWindowAddressTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne informacije.
        /// </summary>
        public static string PatientWindowBasicInfo {
            get {
                return ResourceManager.GetString("PatientWindowBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krvna grupa.
        /// </summary>
        public static string PatientWindowBloodTypeTb {
            get {
                return ResourceManager.GetString("PatientWindowBloodTypeTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkažite.
        /// </summary>
        public static string PatientWindowCancelBtn {
            get {
                return ResourceManager.GetString("PatientWindowCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zdravstvenog kartona.
        /// </summary>
        public static string PatientWindowCardNumberTb {
            get {
                return ResourceManager.GetString("PatientWindowCardNumberTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto rođenja.
        /// </summary>
        public static string PatientWindowCityTb {
            get {
                return ResourceManager.GetString("PatientWindowCityTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra dijagnoze.
        /// </summary>
        public static string PatientWindowCodeDG {
            get {
                return ResourceManager.GetString("PatientWindowCodeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt informacije.
        /// </summary>
        public static string PatientWindowContactInfo {
            get {
                return ResourceManager.GetString("PatientWindowContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vrijeme pregleda.
        /// </summary>
        public static string PatientWindowDateDG {
            get {
                return ResourceManager.GetString("PatientWindowDateDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string PatientWindowDateDP {
            get {
                return ResourceManager.GetString("PatientWindowDateDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vrijeme naručenja.
        /// </summary>
        public static string PatientWindowDateTab3DG {
            get {
                return ResourceManager.GetString("PatientWindowDateTab3DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum preboljenja.
        /// </summary>
        public static string PatientWindowDateTab4DG {
            get {
                return ResourceManager.GetString("PatientWindowDateTab4DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljne informacije.
        /// </summary>
        public static string PatientWindowDetailedInfo {
            get {
                return ResourceManager.GetString("PatientWindowDetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string PatientWindowDoctorDG {
            get {
                return ResourceManager.GetString("PatientWindowDoctorDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string PatientWindowDoctorTab3DG {
            get {
                return ResourceManager.GetString("PatientWindowDoctorTab3DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljekar.
        /// </summary>
        public static string PatientWindowDoctorTab4DG {
            get {
                return ResourceManager.GetString("PatientWindowDoctorTab4DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string PatientWindowEmailTb {
            get {
                return ResourceManager.GetString("PatientWindowEmailTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta pregleda.
        /// </summary>
        public static string PatientWindowExamTypeDG {
            get {
                return ResourceManager.GetString("PatientWindowExamTypeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string PatientWindowFirstNameTb {
            get {
                return ResourceManager.GetString("PatientWindowFirstNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv bolesti.
        /// </summary>
        public static string PatientWindowIllnessTab4DG {
            get {
                return ResourceManager.GetString("PatientWindowIllnessTab4DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        public static string PatientWindowJmbTb {
            get {
                return ResourceManager.GetString("PatientWindowJmbTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string PatientWindowLastNameTb {
            get {
                return ResourceManager.GetString("PatientWindowLastNameTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bračni status.
        /// </summary>
        public static string PatientWindowMarriageTb {
            get {
                return ResourceManager.GetString("PatientWindowMarriageTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte novo naručenje.
        /// </summary>
        public static string PatientWindowNewAppointmentBtn {
            get {
                return ResourceManager.GetString("PatientWindowNewAppointmentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt telefon.
        /// </summary>
        public static string PatientWindowPhoneTb {
            get {
                return ResourceManager.GetString("PatientWindowPhoneTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlog.
        /// </summary>
        public static string PatientWindowReasonTab3DG {
            get {
                return ResourceManager.GetString("PatientWindowReasonTab3DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvajte.
        /// </summary>
        public static string PatientWindowSavebtn {
            get {
                return ResourceManager.GetString("PatientWindowSavebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o pacijentu.
        /// </summary>
        public static string PatientWindowTab1 {
            get {
                return ResourceManager.GetString("PatientWindowTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi pacijenta.
        /// </summary>
        public static string PatientWindowTab2 {
            get {
                return ResourceManager.GetString("PatientWindowTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naručenja pacijenta.
        /// </summary>
        public static string PatientWindowTab3 {
            get {
                return ResourceManager.GetString("PatientWindowTab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preboljenja pacijenta.
        /// </summary>
        public static string PatientWindowTab4 {
            get {
                return ResourceManager.GetString("PatientWindowTab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled pacijenta.
        /// </summary>
        public static string PatientWindowTitle {
            get {
                return ResourceManager.GetString("PatientWindowTitle", resourceCulture);
            }
        }
    }
}
